experiment:
  name: "Mamba2 Full Seqs ESM2 Single Custom HPY"
  seed: 999

model:
  module: "models.mamba2_esm"
  class_name: "Mamba2ESMClassifier"
  uses_attention: true
  init_args:
    embedding_dim: 640
    model_dim: 256
    state_dim: 64
    expand_factor: 2
    num_ssm_blocks: 6
    dropout: 0.2
    num_classes: 3
    pooling_mode: "attention"

data:
  dataset_type: "full_seqs"
  ecs_only_regions: none
  # Specify the split strategy to use for embedding the sequences in MSA mode (random, balanced, family, diverse), none if not using MSA mode or MSA Transformer
  split_strategy: none

embedder:
  name: "esm2"
  use_msa_mode: false

evaluation:
  mode: "single"
  test_data: "test_2_4_10a_10b_14_19_zf_Cldna-like.fasta"
  test_data_labels: [1, 0, 2, 1, 0, 0, 1] # {0: 'barrier', 1: 'cation', 2: 'anion'} optional

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"

hyperparameters:
  use_custom_hyperparameters: true
  optimizer_lr: 1e-4
  optimizer_weight_decay: 1e-5
  schedular_patience: 10
  warmup_epochs: 5
  useWeightedSampler: false
  weighted_ce_power: false
  num_epochs: none
  batch_size: 128
  patience: none
