experiment:
  name: "Simple Linear Full Seqs MSA Grouped"
  seed: 999

model:
  module: "models.simple_linear"
  class_name: "SimpleLinearClassifier"
  uses_attention: false

data:
  dataset_type: "full_seqs"
  use_msa_mode: true

evaluation:
  mode: "grouped"
  test_data: "Explain_humanCldn2-10a-15-17.fasta"

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"