experiment:
  name: "Simple Linear Full Seqs MSA Single Split Balanced Distribution"
  seed: 999

model:
  module: "models.simple_linear"
  class_name: "SimpleLinearClassifier"
  uses_attention: false

data:
  dataset_type: "full_seqs"
  # Specify the split strategy to use for embedding the sequences in MSA mode (random, balanced, family, diverse)
  split_strategy: "balanced"

embedder:
  name: "msa_transformer"
  use_msa_mode: true

evaluation:
  mode: "single"
  test_data: "test_2_4_10a_10b_14_19_zf_Cldna-like.fasta"
  test_data_labels: [0, 0, 2, 1, 0, 0, 1] # {0: 'barrier', 1: 'cation', 2: 'anion'} optional

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"

hyperparameters:
  # Whether to run hyperparameter tuning for grouped holdout or provide custom set of values
  use_custom_hyperparameters: false
  # If not running hyperparameter tuning, these values will be used directly for training and evaluation
  # Else leave empty
  optimizer_lr: 
  optimizer_weight_decay: 
  schedular_patience: 
  warmup_epochs: 
  useWeightedSampler: 
  weighted_ce_power: 
  num_epochs: 
  batch_size: 
  patience: 