experiment:
  name: "Simple Linear ECS only Non-MSA Single Split"
  seed: 999

model:
  module: "models.simple_linear"
  class_name: "SimpleLinearClassifier"
  uses_attention: false

data:
  dataset_type: "ecs_only"
  # If ECS only, specify the regions to cut, else keep empty
  ecs_only_regions: [[28, 81], [139, 164]]
  # Specify the split strategy to use for embedding the sequences in MSA mode (random, balanced, family, diverse), none if not using MSA mode or MSA Transformer
  split_strategy: none

embedder:
  name: "msa_transformer"
  use_msa_mode: false

evaluation:
  mode: "single"
  test_data: "test_2_4_10a_10b_14_19_zf_Cldna-like.fasta"
  test_data_labels: [1, 0, 2, 1, 0, 0, 2] # {0: 'barrier', 1: 'cation', 2: 'anion'} optional

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"

hyperparameters:
  # Whether to run hyperparameter tuning for grouped holdout or provide custom set of values
  use_custom_hyperparameters: false
  # If not running hyperparameter tuning, these values will be used directly for training and evaluation
  # Else leave empty
  optimizer_lr: 
  optimizer_weight_decay: 
  schedular_patience: 
  warmup_epochs: 
  useWeightedSampler: 
  weighted_ce_power: 
  num_epochs: 
  batch_size: 
  patience: 