experiment:
  name: "Transformer MLP Full Seqs MSA Single Random Distribution"
  seed: 999

model:
  module: "models.transformer_mlp"
  class_name: "TransformerMLPClassifier"
  uses_attention: true
  init_args:
    max_seq_len: 190

data:
  dataset_type: "full_seqs"
  # If ECS only, specify the regions to cut, else keep empty
  ecs_only_regions: none
  # Specify the split strategy to use for embedding the sequences in MSA mode (random, balanced, family, diverse)
  split_strategy: "random"

embedder:
  name: "msa_transformer"
  use_msa_mode: true

evaluation:
  mode: "single"
  test_data: "Explain_humanCldn2-10a-15-17.fasta"

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"

hyperparameters:
  # Whether to run hyperparameter tuning for grouped holdout or provide custom set of values
  use_custom_hyperparameters: false
  # If not running hyperparameter tuning, these values will be used directly for training and evaluation
  # Else leave empty
  optimizer_lr: none
  optimizer_weight_decay: none
  schedular_patience: none
  warmup_epochs: none
  useWeightedSampler: none
  weighted_ce_power: none
  num_epochs: none
  batch_size: none
  patience: none