experiment:
  name: "Transformer MLP Gaussian Noise Full Seqs MSA Single"
  seed: 999

model:
  module: "models.transformer_mlp_gaussian_noise"
  class_name: "TransformerMLPClassifier"
  uses_attention: true

data:
  dataset_type: "full_seqs"
  # If ECS only, specify the regions to cut, else keep empty
  ecs_only_regions: none
  init_args:
    max_seq_len: 220

embedder:
  name: "msa_transformer"
  use_msa_mode: true

evaluation:
  mode: "single"
  test_data: "Explain_humanCldn2-10a-15-17.fasta"

path:
  runs_root: "/content/drive/MyDrive/Thesis data/runs"

hyperparameters:
  # Whether to run hyperparameter tuning for grouped holdout or provide custom set of values
  use_custom_hyperparameters: true
  # If not running hyperparameter tuning, these values will be used directly for training and evaluation
  # Else leave empty
  optimizer_lr: 1e-4
  optimizer_weight_decay: 1e-5
  schedular_patience: 10
  warmup_epochs: 3
  useWeightedSampler: false
  weighted_ce_power: false
  num_epochs: none
  batch_size: 128
  patience: none