experiment:
  name: "Transformer MLP Full Seqs MSA Grouped"
  seed: 999

model:
  module: "models.transformer_mlp"
  class_name: "TransformerMLPClassifier"
  uses_attention: true

data:
  dataset_type: "full_seqs"
  use_msa_mode: true

evaluation:
  mode: "grouped"
  test_data: "Explain_humanCldn2-10a-15-17.fasta"

path:
  runs_root: "drive/MyDrive/Thesis data/runs"